export default Object.freeze({
    ERROR_NOT_AUTHENTICATED: "ERROR_NOT_AUTHENTICATED",
    ERROR_NOT_AUTHORIZED: "ERROR_NOT_AUTHORIZED",
    ERROR_NOT_FOUND: "ERROR_NOT_FOUND",
    ERROR_BAD_REQUEST: "ERROR_BAD_REQUEST",
    ERROR_SERVICE_FAILURE: "ERROR_SERVICE_FAILURE"
});